FROM python:3.7-slim-buster

WORKDIR /app
RUN apt-get update && \
    apt-get install -y \
        libcurl4-openssl-dev \
        libboost-python-dev \
        libgtk2.0-dev \
        libglib2.0-0
RUN apt-get install -y build-essential cmake \
        libopenblas-dev \
        liblapack-dev \
        libopenblas-dev \
        liblapack-dev

COPY requirements.txt ./



RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]